Enable manual runs of test.yml
Manual runs of this action will allow easier troubleshooting of the serialization error detected in https://github.com/aiarena/sc2-ai-match-controller/actions/runs/12427001493/job/34696124482 on step "Run file-based integration tests":

```
Attaching to bot_controller1-1, bot_controller2-1, proxy_controller-1, sc2_controller-1
proxy_controller-1  | thread 'main' panicked at proxy_controller/src/main.rs:173:10:
proxy_controller-1  | Could not deserialize config: missing field `arena_client_id`
proxy_controller-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborting on container exit...
```